name: ani-shedule

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install tqdm==4.63.0
        pip install lxml==5.2.2
        pip install requests==2.32.3
        pip install prompt-toolkit==3.0.43

    - name: Build package
      run: python -m build

    - name: Install package
      run: |
        pip install .

    - name: Verify installation
      run: |
        which ani-shedule
        ani-shedule

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
